### ISSUE TITLE
Some buffers are stored on CPU when training "extended" model on GPU

### ISSUE THREAD

**Issue by YiifeiWang** [f-dangel/backpack#97]
When I train an extended model on GPU, some of the buffers in the model will store on CPU, which leads to certain runtime error. I use the following code for extending model:
`
net = extend(net)
net = torch.nn.DataParallel(net)
net = net.to('cuda')
`
In practical training, everything goes fine in the first epoch for training and buffers are stored on cuda. When it starts to test, all buffers appear to be stored on cpu.

My current strategy is to add a line
`
net = net.to('cuda')
`
in each iteration of training/testing.

This problem does not appear if I do not use `net = extend(net)`.

Hope that this problem can be solved

**Comment by fKunstner** [comment]
Hi Yifei, thanks for reaching out! That does sound like a bug. 
Do you have a minimal example, say on a linear model on random artificial data? That'd would be helpful to pinpoint what's happening. 

Some additional questions would be:
- What buffers are causing the problem? I assume it's the additional buffers stored by Backpack given that it does not happen otherwise, but the error that you get would be helpful
- What's the difference between the training setup and the testing setup? Is it only a case of "there is no backward() in the testing code" or are there additional differences like `model.train()/model.eval()` are being called?
- Does this also happen if you don't use `DataParallel`?

**Comment by YiifeiWang** [comment]
Hi Kunstner, attached please find a toy example. 
[toy.py.zip](https://github.com/f-dangel/backpack/files/5080007/toy.py.zip)
To use this code, simply use the following command
python3 toy.py --save_logs toy/ --model CNN3L --optim sgd --backpack --batch_size 1024 --debug --parallel --writeover

- Actually all buffers cause this problem. I list some outputs of the program as follows.

42, conv1.weight cuda:0
42, conv1.bias cuda:0
42, conv2.weight cuda:0
42, conv2.bias cuda:0
42, conv3.weight cuda:0
42, conv3.bias cuda:0
42, input0_shape cpu
42, output_shape cpu
42, conv1.input0_shape cpu
42, conv1.output_shape cpu
42, pool.input0_shape cpu
42, pool.output_shape cpu
42, conv2.input0_shape cpu
42, conv2.output_shape cpu
42, conv3.input0_shape cpu
42, conv3.output_shape cpu

- The training setup and the testing setup can be seen in the code of toy example.

- This also happen if I do not use `DataParallel`.

**Comment by f-dangel** [comment]
Hi Yifei,

your problem should be solved in the version on `development`. Can you confirm this by installing it (I think the command should be `pip install git+https://github.com/f-dangel/backpack.git@development#egg=backpack`) and trying to reproduce your problem?

Thanks again for reporting the issue.
